// Documentul inteligenta-artificiala, in engleza americana, pentru operatorul din Republica Moldova (familia md).
// Convertit o singura data din pachetul juridic 3s.md (blocul de text publicabil), cuvant cu cuvant.
// Sursa: 08-ai-notice.en.md, sha256 890712a2bae291f35ffa97f58e0c4b70580eefcebf87cacc0ccbb6e7201062b5.
// Din ziua conversiei modulul e sursa unica a textului: se editeaza aici, iar pachetul ramane arhiva.
// Conditiile (`conditie`, `daca`) si legaturile interne (`cale:<cheie>`) le rezolva `../index.ts`.

import type { DocumentJuridic } from "../tipuri";
import type { ContextMd } from "./context";

export default function inteligentaArtificialaEn(c: ContextMd): DocumentJuridic {
  return {
    cheie: "inteligenta-artificiala",
    limba: "en",
    titlu: "Artificial intelligence in 3S services",
    versiune: "2026-10-01",
    introducere: "",
    preambul: [
      { jurisdictie: null, paragrafe: ["3S Demerzel SRL is in the process of registration. Until it is registered we issue no offers, enter into no contracts and open no accounts, so the assistant described on this page is not yet offered to clients. This page shows how it will work."] },
      { jurisdictie: null, paragrafe: ["The 3S services, provided by 3S Demerzel SRL of the Republic of Moldova (its details are in the [Legal notice](cale:informatii-legale)), use an artificial intelligence (AI) assistant that answers questions about the Client's documents. This page says what the assistant does, what its limits are and what happens to the documents. It supplements the notice in the chat without replacing it: the assistant tells you that it is an AI system from the start of every conversation (section 2). The notice in the chat and this page take account of the transparency requirements of Article 50 of Regulation (EU) 2024/1689 (the Artificial Intelligence Act), to the extent that they apply. \"Client\" and \"User\" have the meaning given in the [Terms and conditions](cale:termeni).", "**In brief** (a summary with no contractual value; the text below governs)"], lista: { elemente: ["The assistant is an AI system, not a person. It tells you so from the start of every conversation.", "Answers are generated automatically and may be incomplete or wrong. Check the cited document before relying on them.", "Indicating the exact page of the source is in pilot and may be missing or wrong.", "Your documents are processed only to provide the service, under the data processing agreement (DPA).", "You can always speak to a person: " + c.contact.email + " or " + c.contact.telefon + "."] } },
    ],
    sectiuni: [
      {
        cheie: "s1", titlu: "1. What the assistant is and what it does",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The assistant is an AI system. It receives a User's question, searches the Client's documents and formulates an answer in text. It shows the sources on which the answer relies. It does not modify the documents.", "Its purpose is searching the Client's documents and answering questions about them. It is not intended to evaluate people, for example in selecting candidates or assessing creditworthiness, and it does not take decisions in your place."] },
        ],
      },
      {
        cheie: "s2", titlu: "2. How you know you are talking to an AI system",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The assistant tells you clearly, from the start, that it is an AI system and not a person: in the browser chat, through a message when the conversation opens and an \"AI\" badge next to the question field, visible for as long as the conversation lasts.", "This page supplements the notice in the chat; it does not replace it (Regulation (EU) 2024/1689, Art. 50(1) and (5))."] },
        ],
      },
      {
        cheie: "s3", titlu: "3. What is generated by AI",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The text of the answers is generated automatically, on the basis of the question and the Client's documents. The documents themselves are not generated by the assistant and are not modified by it. An answer may summarize or reword the documents without reproducing them; treat it as generated text."] },
        ],
      },
      {
        cheie: "s4", titlu: "4. The limits of the answers",
        blocuri: [
          { jurisdictie: null, paragrafe: [], lista: { elemente: ["An answer may be incomplete, wrong or imprecisely worded. 3S does not guarantee that an answer is correct or complete (Terms, section 7.1).", "The risk is higher on poor scans, handwriting, stamps and tables, figures, dates and proper names.", "Text extracted from scans by optical character recognition may contain errors, and an extraction error reaches the answer.", "The assistant sees only the documents uploaded and indexed in the Account. It cannot find what is missing from the archive, and the absence of a document from an answer does not prove that the document does not exist.", "The same question, asked twice, may receive differently worded answers.", "The assistant does not give legal, accounting or tax advice."] } },
        ],
      },
      {
        cheie: "s5", titlu: "5. Sources and the exact page",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The assistant indicates the documents on which it bases its answer. Indicating the exact page in the document is in pilot: we are testing it together with clients, and the indication may be missing or wrong. Open the document and check before you rely on the answer (Terms, section 7.2)."] },
        ],
      },
      {
        cheie: "s6", titlu: "6. Language",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The result depends on the language of the documents, the language of the question and the quality of the scan. Questions in English about documents in Romanian are in pilot."] },
        ],
      },
      {
        cheie: "s7", titlu: "7. What the Terms do not allow",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The Terms (section 7.3) do not allow the assistant to be used, without 3S's written consent, as a component of a system intended for a use listed in Annex III to Regulation (EU) 2024/1689, for example selecting and evaluating job candidates or assessing the creditworthiness of natural persons, nor as the sole basis for a decision with legal effects on a person (Regulation (EU) 2016/679, Art. 22). The acceptable use rules are also in [Notice and action](cale:notificare-si-actiune), section 7.2."] },
        ],
      },
      {
        cheie: "s8", titlu: "8. Your documents and the AI models",
        blocuri: [
          { jurisdictie: null, paragrafe: ["AI models receive only text: the passages of the documents retrieved for the question or extracted from a specific document, the titles, the folder names, the metadata and the conversation history, and, at indexing, the text of the documents, in chunks. They receive it only to provide the service, under the [data processing agreement](cale:dpa) (DPA). The models and the text recognition run at a sub-processor listed on the page [Sub-processors of the platform](cale:subimputerniciti); the model providers do not receive the documents. The agreement also contains 3S's commitment on the training of AI models (Art. 4.5). How the personal data in the documents is processed is described in the DPA and in the [Privacy policy](cale:confidentialitate)."] },
        ],
      },
      {
        cheie: "s9", titlu: "9. How to reach a person",
        blocuri: [
          { jurisdictie: null, paragrafe: ["You can always contact us directly, without going through the assistant: at " + c.contact.email + " or on WhatsApp at " + c.contact.telefon + " (messages and calls). A person replies, in English or Romanian."] },
        ],
      },
      {
        cheie: "s10", titlu: "10. How to report a problem",
        blocuri: [
          { jurisdictie: null, paragrafe: ["If the assistant gave an answer that is wrong, misleading or inappropriate, write to " + c.contact.email + ", with the question, the answer and the date and time of the conversation; we will look into it. If you think an answer contains unlawful information, use the procedure on the page [Notice and action](cale:notificare-si-actiune)."] },
        ],
      },
      {
        cheie: "s11", titlu: "11. What we guarantee and what we do not",
        blocuri: [
          { jurisdictie: null, paragrafe: ["Answers may be incomplete or wrong, the Client checks the cited document and is responsible for the decisions it takes on the basis of them. That is what the Terms say, in section 7, and the limits of liability are in section 13. This page adds no guarantees and adds no obligations for the Client."] },
        ],
      },
      {
        cheie: "s12", titlu: "12. Language of this page",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The page exists in Romanian and in English. The Romanian version is the authentic one, and the English version is a translation; if the texts differ, the Romanian one applies."] },
        ],
      },
      {
        cheie: "t13", titlu: "Acts cited",
        blocuri: [
          { jurisdictie: null, paragrafe: ["The texts were read on September 30, 2026."], lista: { elemente: ["[Regulation (EU) 2024/1689 (Artificial Intelligence Act)](https://eur-lex.europa.eu/eli/reg/2024/1689/oj)", "[Regulation (EU) 2016/679 (GDPR)](https://eur-lex.europa.eu/eli/reg/2016/679/oj)"] } },
        ],
      },
    ],
  };
}
